version: '3.9'

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    ports:
      - "9094:9094"

  connect:
    image: debezium/connect:3.0.0.Final
    depends_on:
      - kafka
    environment:
      BOOTSTRAP_SERVERS: "kafka:9092"
      GROUP_ID: "debezium-group"
      CONFIG_STORAGE_TOPIC: "debezium-configs"
      OFFSET_STORAGE_TOPIC: "debezium-offsets"
      STATUS_STORAGE_TOPIC: "debezium-status"
    ports:
      - "8083:8083"

  mysql:
    image: mysql:5.7.38
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: servicedb
    volumes:
      - ./my.cnf:/etc/mysql/my.cnf # Since log bin might not be enabled
      - ./init:/docker-entrypoint-initdb.d # create user and give privileges
    ports:
      - "3306:3306"
